### ISSUE TITLE
没有关闭方法，是否考虑添加一个

### ISSUE THREAD

**Issue by gavinning** [jkchao/vue-loading#1]
这是一个很棒的组件，内置了很多漂亮的loading
但是没有发现关闭的方法，是否考虑添加一个，或者添加一个控制显示关闭的prop属性，或者是显示关闭的事件监听等等
因为loading是根据产品需要来显示和隐藏的，所以我想这个比较重要

我尝试在引用时添加hide属性，结果发现vue并不允许这么做，当然也或许是我用法有问题😂

**Comment by jkchao** [comment]
@gavinning 不好意思，现在才看到。
可以试下这个`<vue-loading v-if=""></vue-loading>`, `v-if`绑定一个`Boolean`。

**Comment by gavinning** [comment]
谢谢，搞定 ~
