### ISSUE TITLE
有部分版本的ios系统使用这个库导致页面白屏

### ISSUE THREAD

**Issue by Richard-Choooou** [jkchao/vue-loading#18]

**Comment by jkchao** [comment]
是不是这个原因 https://github.com/jkchao/vue-loading/issues/13

**Comment by parox2014** [comment]
@jkchao 应该不是这个原因，打包的时候没报错，但在IOS9中，页面加载时会提示一个错误：

`SyntaxError:Unexpected identifier 'i' /app.js`

导致应用无法启动，我也是查了好久，才找到原因，去掉这个插件，就好了，怀疑是不是某个变量使用之前未声明

**Comment by parox2014** [comment]
找到原因了，vueLoading.common.js里面，居然有个let ，而默认node_modules里的文件是不会进行编译的，导致低版的浏览器无法识别，

**Comment by jkchao** [comment]
是的，这里打包出了一点问题，暂时还没搞明白为什么 let 没被转化成 var

**Comment by Richard-Choooou** [comment]
@parox2014 是的，我也是这个原因，去掉这个库就好了，只是没找到这个let, 你牛

**Comment by Richard-Choooou** [comment]
@jkchao 看看是不是babel版本的问题

**Comment by jkchao** [comment]
resolved.
