### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by santiblanko** [jkchao/vue-loading#2]
How I can change the styles of the component?
I want the blue dotted style!

**Comment by jiamianmao** [comment]
You are so naughty~

**Comment by santiblanko** [comment]
<img width="1280" alt="captura de pantalla 2017-05-27 a las 11 18 59 a m" src="https://cloud.githubusercontent.com/assets/5376762/26522811/5214d218-42ce-11e7-800d-2dcbdee9ccf6.png">
