### ISSUE TITLE
Component not rendering on the screen

### ISSUE THREAD

**Issue by devlemire** [jkchao/vue-loading#20]
I'm not sure what exactly I am doing wrong. I tried the global installation and the component level installation, and I cannot get anything to appear on the screen.

Is this just me? I'm confused.

**Comment by jkchao** [comment]
Is there an error?

**Comment by devlemire** [comment]
No error, it just doesn't render. I'm baffled. This isn't my first time using something like this either.

**Comment by jkchao** [comment]
You can try again, I solved a bug.
