### ISSUE TITLE
请问build的index 是怎么生成的？

### ISSUE THREAD

**Issue by gdutwyg** [jkchao/vue-loading#5]
看你的代码，貌似没有指令去生成build目录的这个index.js？？？

**Comment by jkchao** [comment]
@gdutwyg build 是 npm run build 出来的东西 - -,

**Comment by gdutwyg** [comment]
@jkchao  应该不是，你可以看一下你的webpack配置，生成的文件是在dist目录的vue-loading.min.js，并且这个文件和build的index.js是不一样的

**Comment by gdutwyg** [comment]
@jkchao  生成build的index.js 应该是不是这个webpack配置

**Comment by jkchao** [comment]
@gdutwyg npm run build 命令在 package.json 这个文件里

**Comment by jkchao** [comment]
@gdutwyg 
有两次打包，第一次是打包静态页面，也就是 build 里的东西
```javascript
 // webpack  
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './build'),
    publicPath: '/build/',
    filename: 'build.js'
  },
```

第二次打包出 dist 下的东西。

**Comment by gdutwyg** [comment]
@jkchao  请问dist 文件下vue-loading.min.js 是怎么使用的？能给个例子吗？ 我用cdn的方式去使用没有效果。。。

**Comment by jkchao** [comment]
@gdutwyg 不支持 UMD 方式 😀

**Comment by gdutwyg** [comment]
@jkchao  那这个vue-loading.min.js 是怎么个使用方法呢？能给个例子吗？

**Comment by jkchao** [comment]
@gdutwyg
```javascript
 import loadTemplate from './vue-loading.min.js' 
```
